on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: bugdriver/publish-react@v2
        with:
          server_repo: 'shiviraj/counterServer'
          react_repo: 'shiviraj/counter'
          heroku_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'shiviraj-counter'
          github_user_email: 'raj.shiviraj@gmail.com'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
